### ISSUE TITLE
청원게시판 리스트 Response DTO 변경 요쳥

### ISSUE THREAD

**Issue by jaem0629** [DKU54PLAY/student-council-homepage-backend-rtsjou#226]
![Screenshot 2023-03-16 at 3 28 06 PM](https://user-images.githubusercontent.com/91131509/225533169-99132f1c-8506-4704-9eeb-a3fa45b86256.png)
최소한 제목, 청원 마감일, 청원 시작일, 참여인원, 청원상태를 불러올 수 있어야함

**Comment by jaem0629** [comment]
![Screenshot 2023-03-16 at 4 20 01 PM](https://user-images.githubusercontent.com/91131509/225542998-570de89b-c45e-4a42-8014-bcdf204a2c36.png)
그리고 리스트 조회할 때 청원상태 쿼리로 카테고리 정해서 불러올 수 있어야함

**Comment by won983212** [comment]
다른 레포지토리로 이동
https://github.com/DKUcouncilhomepage/student-council-homepage-backend/issues/123#issue-1627708576
